setting:
  browser: chrome
  db: sqlite:///data.db
  headless: false
  link_url: https://nicelink18.com/
  timeout: 10
  tries: 5
  use_upscale: false
site:
- class_name: Wfwf
  download_path: ./comics
  file_extensions: cbz
  filter:
  - https://wfwf[0-9]+.com/cl\?toon=[0-9]+
  name: wfwf
  title: 늑대 닷컴
  url: https://wfwf287.com
  url_format:
    chapter:
      condition: /html/body/section[1]/div[5]/img
      filter: /cv?toon={0}&num={1}
      re: /cv?toon=(\d+)
    title:
      condition: //*[@id="content"]/div[2]/div[3]/h1
      filter: /cl?toon={0}
      re: .*/cl\?toon=\D*(\d+)
- class_name: Wfwf
  download_path: ./webtoon
  file_extensions: cbz
  filter:
  - https://wfwf[0-9]+.com/list\?toon=[0-9]+
  name: wftoon
  title: 늑대 닷컴
  url: https://wfwf287.com
  url_format:
    chapter:
      condition: /html/body/section[1]/div[5]/img
      filter: /view?toon={0}&num={1}
      re: /view?toon=(\d+)
    title:
      condition: //*[@id="content"]/div[2]/div[3]/h1
      filter: /list?toon={0}
      re: .*/list\?toon=\D*(\d+)
