setting:
  browser: firefox
  db: sqlite:///data.db
  headless: false
  link_url: https://nicelink18.com/
  timeout: 10
  tries: 5
site:
- class_name: Wfwf
  download_path: ./comics
  file_extensions: cbz
  filter:
  - https://wfwf[0-9]+.com/cl\?toon=[0-9]+
  name: wfwf
  title: 늑대 닷컴
  url: https://wfwf222.com
  url_format:
    chapter:
      filter: /cv?toon={0}&num={1}
      re: /cv?toon=(\d+)
      visible_condition:
        text: /html/body/section[1]/div[5]/img
        type: xpath
    title:
      filter: /cl?toon={0}
      re: .*/cl\?toon=\D*(\d+)
      visible_condition:
        text: //*[@id="content"]/div[2]/div[3]/h1
        type: xpath
- class_name: Wfwf
  download_path: ./webtoon
  file_extensions: cbz
  filter:
  - https://wfwf[0-9]+.com/list\?toon=[0-9]+
  name: wftoon 
  title: 늑대 닷컴
  url: https://wfwf222.com
  url_format:
    chapter:
      filter: /view?toon={0}&num={1}
      re: /view?toon=(\d+)
      visible_condition:
        text: /html/body/section[1]/div[5]/img
        type: xpath
    title:
      filter: /list?toon={0}
      re: .*/list\?toon=\D*(\d+)
      visible_condition:
        text: //*[@id="content"]/div[2]/div[3]/h1
        type: xpath

